name: workflow 


on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'

permissions:
   id-token: write
   contents: read 

jobs:
  integration:
    name: : Continues Integration
    runs-on: ubuntu-latest
    steps:
     - name: Checkout Code 
       uses: actions/checkout@v3 
     with:
      repository: bimal-bp/mlops_deep_learning_project 
      token: ${{secrets.GITHUB_TOKEN}}
      ref: main 

    - name : Lint code 
      run: echo "Linting Repositiry"
    - name: Run unit tests
      run: echo "Running unit tests"


  push_to_registry:
    name: puch Docker image to Docker hub 
    runs-on : ubuntu-latest
    steps:
      - name: Checkout out the repo 
        uses: actions/checkout@v3
      
      - name: Setup Docker Build 
        uses: docker/setup-build-action@v2
      - name: Login to ducker hub 
        uses: docker/loging-action@745849574638204739

        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}


      - name: Extra metadata(tags,labels) for docker 
        id: meta
        uses: docker/metadata-actio@jdfjdjrhfierueh8347383783
        with:
          images: ${{secrets.REGISTRY}}/${{secrets.IMAGE_NAME}}

      - name: Build and Push Docker image 
        uses: docker/build-push-actions@v2
        with: 
          contetx: "{{defaultContext}}"
          push: true
          tags: ${{steps.meta.outputs.tags}}
          labels: ${{steps.meta.outputs.labels}}
